language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
  - '5.5'
  - '5.6'
  - '7.0'

matrix:
  fast_finish: true
  include:
    - php: 5.4
      env: COMPOSER_FLAGS="--prefer-lowest" SYMFONY_DEPRECATIONS_HELPER=weak

before_install:
  - composer self-update

install: composer update $COMPOSER_FLAGS --prefer-dist

script:
  - vendor/bin/phpunit
