language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  fast_finish: true
  include:
    - php: 5.5
      env: COMPOSER_FLAGS="--prefer-lowest" SYMFONY_DEPRECATIONS_HELPER=weak
    - php: 5.6
    - php: 7.0
    - php: 7.1

before_install:
  - composer self-update

install:
  - composer update $COMPOSER_FLAGS --prefer-dist

script:
  - vendor/bin/phpunit
